* groupby operation
- grouping data
- aggregation 
- multiple aggregation
- transform  of filter 
- pivot table

### groupby     

- the groupby function use to split tha data into group base on one or more columns after grouping we can perfrome calculation of ecah group

In [16]:
import pandas as pd
dic = { "id":[101,102,103,104],
       "name":['Aa',"Aa","Cc","Dd"]
       ,'age':[20,90,30,None]
       }
dic1= {"id":[2,3,4,5],
       "name":['A',"B","C","D"]
       }
df1 = pd.DataFrame(dic)
df2 = pd.DataFrame(dic1)
df1.groupby("name")

In [19]:
dic = { "id":[101,102,103,104],
       "name":['Aa',"Aa","Cc","Dd"]
       ,'age':[20,90,30,None]
       }
df1 = pd.DataFrame(dic)
df1.groupby('name')['age'].sum()

name
Aa    110.0
Cc     30.0
Dd      0.0
Name: age, dtype: float64

In [22]:
dic = { "id":[101,102,103,104],
       "name":['Aa',"Aa","Cc","Dd"]
       ,'age':[20,90,30,None]
       ,'marks':[45,55,65,75]
       }
df1 = pd.DataFrame(dic)
df1.groupby('name')['age'].agg(['sum','count'])
df1.groupby('name')['age'].agg(['sum','count','max'])

        sum  count   max
name
Aa    110.0      2  90.0
Cc     30.0      1  30.0
Dd      0.0      0   NaN

In [28]:
import pandas as pd

dic = { 
    "id":[101,102,103,104],
    "name":['Aa',"Aa","Cc","Dd"],
    "age":[20,90,30,None],
    "marks":[45,55,65,75]
}
df1 = pd.DataFrame(dic)

result = df1.groupby('name').agg({
    'age':['sum','mean'],
    'marks':'count'
})
print(result)

        age       marks
        sum  mean count
name
Aa    110.0  55.0     2
Cc     30.0  30.0     1
Dd      0.0   NaN     1

### transform filter
- it performe a calculation each group return result with same number of original

In [31]:

dic = { 
    "id":[101,102,103,104],
    "name":['Aa',"Aa","Cc","Dd"],
    "age":[20,90,30,None],
    "marks":[45,55,65,75]
}
df1 = pd.DataFrame(dic)
df1['avesalry']= df1.groupby('name')['age'].transform('mean')
print(df1)

    id name   age  marks  avesalry
0  101   Aa  20.0     45      55.0
1  102   Aa  90.0     55      55.0
2  103   Cc  30.0     65      30.0
3  104   Dd   NaN     75       NaN

### filter
- keep only the group that satisfy a condition

In [34]:
df1.groupby('name').filter(lambda x: x ['age'].mean()>25)

    id name   age  marks  avesalry
0  101   Aa  20.0     45      55.0
1  102   Aa  90.0     55      55.0
2  103   Cc  30.0     65      30.0