In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\shive\OneDrive\Desktop\Data-science-journey\Pandas\basics\ecommerce_data_200_rows_.csv")
print(df.head(10))

   OrderID Customer     Product     Category  Price       City
0     1001     Liam       Mouse  Electronics    700    Chennai
1     1002  Charlie       Shoes      Fashion   2500      Delhi
2     1003     Jack    Backpack      Fashion   2200     Jaipur
3     1004      Bob      Laptop  Electronics  55000       Pune
4     1005     Jack       Shoes      Fashion   2500    Kolkata
5     1006     Liam    Backpack      Fashion   2200  Bengaluru
6     1007    Henry  Headphones  Electronics   1800    Chennai
7     1008     Liam      Laptop  Electronics  55000     Jaipur
8     1009  Charlie        Book        Books    450       Pune
9     1010      Bob        Book        Books    450     Jaipur

In [8]:
df.to_csv("cleaned_data.csv",index=False)
df.head(10)

   OrderID Customer     Product     Category  Price       City
0     1001     Liam       Mouse  Electronics    700    Chennai
1     1002  Charlie       Shoes      Fashion   2500      Delhi
2     1003     Jack    Backpack      Fashion   2200     Jaipur
3     1004      Bob      Laptop  Electronics  55000       Pune
4     1005     Jack       Shoes      Fashion   2500    Kolkata
5     1006     Liam    Backpack      Fashion   2200  Bengaluru
6     1007    Henry  Headphones  Electronics   1800    Chennai
7     1008     Liam      Laptop  Electronics  55000     Jaipur
8     1009  Charlie        Book        Books    450       Pune
9     1010      Bob        Book        Books    450     Jaipur

### Key Attributes:
- pd.read_csv("data.csv", sep=",", header=0, names=None, index_col=None, usecols=None,skiprows=None, nrows=None, na_values=None, dtype=None encoding="utf-8")

- sep → delimiter (, for CSV, \t for tab, ; etc.)

- header → row number to use as column names (0 = first row, None = no header)

- names → custom column names list

- index_col → column(s) to set as index

- usecols → select specific columns

- skiprows → skip certain rows at start

- nrows → read only limited number of rows

- na_values → specify strings to treat as NaN

- dtype → force column data types

- encoding → handle special characters (e.g., "utf-8", "latin1")

In [9]:
df.to_csv("cleaned_data.csv",sep=",")
df

     OrderID Customer     Product     Category  Price       City
0       1001     Liam       Mouse  Electronics    700    Chennai
1       1002  Charlie       Shoes      Fashion   2500      Delhi
2       1003     Jack    Backpack      Fashion   2200     Jaipur
3       1004      Bob      Laptop  Electronics  55000       Pune
4       1005     Jack       Shoes      Fashion   2500    Kolkata
..       ...      ...         ...          ...    ...        ...
195     1196     Liam       Mouse  Electronics    700     Jaipur
196     1197      Mia  Coffee Mug         Home    350       Pune
197     1198    Henry  Coffee Mug         Home    350    Kolkata
198     1199    David       Mouse  Electronics    700     Jaipur
199     1200    Kiran       Shoes      Fashion   2500  Hyderabad

[200 rows x 6 columns]

In [ ]:
df.to_csv("cleaned_data.csv",header=0)
df

     OrderID Customer     Product     Category  Price       City
0       1001     Liam       Mouse  Electronics    700    Chennai
1       1002  Charlie       Shoes      Fashion   2500      Delhi
2       1003     Jack    Backpack      Fashion   2200     Jaipur
3       1004      Bob      Laptop  Electronics  55000       Pune
4       1005     Jack       Shoes      Fashion   2500    Kolkata
..       ...      ...         ...          ...    ...        ...
195     1196     Liam       Mouse  Electronics    700     Jaipur
196     1197      Mia  Coffee Mug         Home    350       Pune
197     1198    Henry  Coffee Mug         Home    350    Kolkata
198     1199    David       Mouse  Electronics    700     Jaipur
199     1200    Kiran       Shoes      Fashion   2500  Hyderabad

[200 rows x 6 columns]

In [25]:
df = pd.read_csv("cleaned_data.csv", sep=";", header=0, usecols=["OrderID","Customer"], nrows=10)
df

ValueError: Usecols do not match columns, columns expected but not found: ['OrderID', 'Customer']